### General ###

set -g default-terminal "xterm-256color"
#set -g default-terminal "screen-256color"
set -g history-limit 10000
set -sg escape-time 1
#set -g repeat-time 700

### 1-based indices
set -g base-index 1
setw -g pane-base-index 1

# don't rename windows automatically
#set-option -g allow-rename off

# vi key bindings
set -g status-keys vi
setw -g mode-keys vi

# mouse
set -g mouse on
#setw -g mouse-mode on

### Prefix ###

set -g prefix C-Space
bind C-Space send-prefix
unbind C-b

### Activity & bells ###

set -g monitor-activity on
set -g visual-activity off
set -g activity-action other
setw -g monitor-bell on
set -g visual-bell off
set -g bell-action other
#set -g visual-silence ?

### Status bar layout ###

set -g status-justify centre
set -g status-left-length 40
set -g status-left "#S #I #P"
set -g status-right-length 100
set -g status-right "#(echo $USER)@#h %b %d %R"

### Key bindings ###

# create panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# move panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# cycle windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

