"leader must be set before keymaps

nnoremap <SPACE> <Nop>
let mapleader = "\<space>"

"custom pairs
nnoremap <silent> [t :tabprev<CR>
nnoremap <silent> ]t :tabnext<CR>

"setup vim-plug
"https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"plugin
call plug#begin()
  Plug 'tpope/vim-commentary'
  Plug 'jeetsukumaran/vim-pythonsense'

  if exists('g:vscode')
    " VSCode extension
    "Plug 'asvetliakov/vim-easymotion', { 'as': 'vsc-easymotion' }
  else
    " ordinary Neovim
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'scrooloose/nerdcommenter'
    Plug 'scrooloose/nerdtree'
    Plug 'tpope/vim-dispatch'
    Plug 'junegunn/vim-peekaboo'
    Plug 'xolox/vim-misc'
    Plug 'xolox/vim-session'
    let g:session_autosave = 'no'
    Plug 'tpope/vim-fugitive'

    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    nnoremap <silent> <Leader>f :Files<CR>
    nnoremap <silent> <Leader>r :Rg<CR>
    nnoremap <silent> <Leader>b :Buffers<CR>
    nnoremap <silent> <Leader>c :Commits<CR>
    nnoremap <silent> <Leader>j :Jumps<CR>

    " use ripgrep for :grep
    set grepprg=rg\ --vimgrep\ --smart-case\ --follow

    "Plug 'jiangmiao/auto-pairs'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-unimpaired'

    Plug 'davidhalter/jedi-vim'

    "Plug 'easymotion/vim-easymotion'
    Plug 'folke/which-key.nvim'
    "Plug 'liuchengxu/vim-which-key' "original
  endif
call plug#end()

"tabs
set tabstop=2
set shiftwidth=0
set softtabstop=2
set expandtab

"don't close unsaved buffers
set hidden

"line numbers
set number
set relativenumber

"highlight search
set hlsearch
"incremental search
set incsearch
"ignore case for all lowercase search
set ignorecase smartcase

"set clipboard=unnamed
"X windows primary/clipboard
"set clipboard=unnamedplus

"for netrw
"not needed after vim 8
set nocompatible
filetype plugin indent on

"turn off last search highlights
nnoremap <silent> <esc><esc> :nohlsearch<return><esc>

"disable normal navigation
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

